[package]
name = "rectangle"
version = "0.1.0"
authors = ["Roger Curley <rocurley@gmail.com>"]
edition = "2024"

[profile.release]
debug = true

[dependencies]
itertools = "0.6.2"
pbr = "1.0.0"
clap = "2.26.0"
ascii = "0.8.6"

[dev-dependencies]
criterion = "0.3"
proptest = "1.6.0"

[[bench]]
name = "main"
harness = false
