[package]
name = "rectangle"
version = "0.1.0"
authors = ["Roger Curley <rocurley@gmail.com>"]

[profile.release]
debug = true

[dependencies]
ndarray = "0.10.5"
itertools = "0.6.2"
pbr = "1.0.0"
fnv = "1.0.5"
cpuprofiler = "0.0.3"
clap = "2.26.0"
